# Generated by Django 6.0.3 on 2026-05-07 07:37

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instrumentfinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentfinder',
            name='query_text_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
