# Generated by Django 6.0.3 on 2026-05-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_collection_options_instrumentfinderresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentfinderresult',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
