# Generated by Django 6.0.3 on 2026-04-06 16:39

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('history', models.TextField(blank=True, help_text='Brief history for LLM context')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('mint', 'Mint (Like New)'), ('excellent', 'Excellent'), ('very_good', 'Very Good'), ('good', 'Good (Player Grade)'), ('fair', 'Fair (Project)')], max_length=50)),
                ('is_original', models.BooleanField(default=True, help_text='Are all parts original?')),
                ('has_repairs', models.BooleanField(default=False)),
                ('is_concert_ready', models.BooleanField(default=False)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_auction', models.BooleanField(default=False)),
                ('auction_end_date', models.DateTimeField(blank=True, null=True)),
                ('text_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('image_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruments', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='instruments/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.instrument')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
