# Generated by Django 6.0.3 on 2026-04-08 09:01

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instrument',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['text_embedding'], m=16, name='text_vector_idx', opclasses=('vector_cosine_ops',)),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['image_embedding'], m=16, name='image_vector_idx', opclasses=('vector_cosine_ops',)),
        ),
    ]
