# Generated by Django 6.0.3 on 2026-04-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_instrument_text_vector_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='year',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
