# Generated by Django 6.0.3 on 2026-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_instrument_updated_at_alter_instrument_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
