# Generated by Django 6.0.3 on 2026-04-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_instrument_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='has_extra_info',
            field=models.BooleanField(default=False),
        ),
    ]
