# Generated by Django 6.0.3 on 2026-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_instrument_has_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
