# Generated by Django 6.0.3 on 2026-04-09 10:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_instrument_updated_at_alter_instrument_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['range_start'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('began_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='registered_auctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_automatic', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amount'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot_number', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('sold', 'Sold'), ('passed', 'Passed (Reserve not met)'), ('withdrawn', 'Withdrawn')], default='waiting', max_length=20)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price to sell', max_digits=12, null=True)),
                ('estimated_price_min', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Low Estimate')),
                ('estimated_price_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='High Estimate')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='auction.auction')),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auction_lot', to='catalog.instrument')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_lots', to=settings.AUTH_USER_MODEL)),
                ('winning_bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_lot_record', to='auction.bid')),
            ],
            options={
                'ordering': ['lot_number'],
                'abstract': False,
                'unique_together': {('auction', 'lot_number')},
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='auction.lot'),
        ),
    ]
