# Generated by Django 6.0.3 on 2026-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='waiting', max_length=20),
        ),
    ]
