# Generated by Django 6.0.3 on 2026-04-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_lot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
