# Generated by Django 6.0.3 on 2026-04-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='min_participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
