# Generated by Django 6.0.3 on 2026-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_max_participants_auction_min_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_interval',
            field=models.PositiveIntegerField(default=60, help_text='Timeout between bids in seconds'),
        ),
        migrations.AddField(
            model_name='lot',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('payment_pending', 'Payment Pending'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='waiting', max_length=20),
        ),
    ]
