# Generated by Django 6.0.3 on 2026-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auction_bid_interval_lot_expires_at_alter_lot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
