# Generated by Django 6.0.3 on 2026-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_lot_payment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='remind_before_start',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes before auction start to send notification', null=True),
        ),
    ]
