# Generated by Django 6.0.3 on 2026-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_remind_before_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='remind_sent',
            field=models.BooleanField(default=False),
        ),
    ]
