"""
Django settings for vintage_hunter project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import environ
from dotenv import load_dotenv
from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _

load_dotenv()
env = environ.Env()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = env.get_value('SECRET_KEY')

DEBUG = True

ALLOWED_HOSTS = ['*']

AZURE_AD_CLIENT_ID = env.get_value('AZURE_CLIENT_ID')
AZURE_AD_CLIENT_SECRET = env.get_value('AZURE_CLIENT_SECRET')

DEFAULT_QUEUE_NAME = env.get_value('CELERY_BROKER_QUEUE')
DEFAULT_PERIODIC_QUEUE_NAME = env.get_value('CELEREY_PERIODIC_BROKER_QUEUE')
STORAGE_ACCOUNT_NAME = env.get_value('AZURE_STORAGE_NAME')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'catalog.apps.CatalogConfig',
    'auction.apps.AuctionConfig',
    'users.apps.UsersConfig',
    'payments.apps.PaymentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

ROOT_URLCONF = 'vintage_hunter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vintage_hunter.wsgi.application'

DATABASES = {
    'default': environ.Env().db('DB_URL')
}

STORAGES = {
    "default": {
        "BACKEND": "commons.storages.AzureMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "commons.storages.AzureStaticStorage",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('uk', _('Ukrainian')),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

STATICFILES_STORAGE = 'commons.storages.AzureStaticStorage'
STATIC_URL = f'https://{STORAGE_ACCOUNT_NAME}.blob.core.windows.net/static/'

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': env.get_value('DJANGO_LOG_LEVEL', default='DEBUG'),
        },
    },
}

REDIS_URL = 'redis://localhost:6379/0'
EMBEDDING_MODEL_PATH = env.get_value('EMBEDDING_MODEL_PATH')
EMBEDDING_IMAGE_MODEL_PATH = env.get_value('EMBEDDING_IMAGE_MODEL_PATH')

PAYMENT_PROVIDER = 'payments.providers.mock.MockPaymentProvider'
